### ISSUE TITLE
Remove external CDN and package bootstrap directly

### ISSUE THREAD

**Issue by bensheldon** [mbajur/inner_performance#13]
This is a great looking Rails Engine! 🙇🏻 

Unfortunately, I can't use it because it has a dependency on Bootstrap delivered by a 3rd party CDN so it won't pass a security review:

https://github.com/mbajur/inner_performance/blob/7bdb3cfb459c808b9ddfed9fffde65c5997fc4c1/app/views/layouts/inner_performance/application.html.erb#L10

It would be awesome for you to vender and serve Bootstrap directly in the Engine. I documented how I did that with GoodJob:

https://island94.org/2023/03/how-goodjob-s-mountable-rails-engine-delivers-javascript-importmaps-and-frontend-assets

And here's a more recent time I set it up in Spectator Sport:

https://github.com/bensheldon/spectator_sport/pull/20

I'd be happy to help too.

**Comment by mbajur** [comment]
Thank you @bensheldon !

I gave that a lot of thoughts before and as much as i don't like serving bootstrap or anything else from CDN, i just went for the simplicity. But that's temporary, unless i figure out how to do that better. My concerns are:

1. I would really wish Bootstrap was part of the gem itself or somehow plugging in to whatever assets engine parent app is using and be served locally but that slightly above my knowledge in this regard so i would need to make a proper research on how to approach that. Article you linked looks interesting and i will definitely look into it once i have more time :)
2. I could just use a boostrap gem but i don't think that's a dependency i want to add to the stack of all the inner_performance users
3. Bootstrap seems a bit like an overkill for such a simple app but on the other hand, it's well know by everyone, anyone can contribute easily and it just looks nice, simple and familiar which all takes off the weight of maintaining and reviewing custom css off my shoulders

I don't have much time to dig into that ATM but i'm super open for resolving that and will welcome any PRs with open arms.

Btw, never heard of spectator_sport before but it looks absolutely awesome and i can't wait to use it. Also great to have an author of my fav and go-to background job processing on board 💪 Thank you for all the great work you do!

**Comment by bensheldon** [comment]
We are in agreement 1000%. 

The approach I've used in GoodJob and Spectator Sport is to vendor and serve the assets out of a custom controller in the gem. It's entirely self contained and kept separate from the patent app's asset pipeline. I even set up a custom importmap declaration for JavaScript; again entirely self contained and without any gem dependencies. 

Let me try to make a quick PR this week of at least the CSS part of it.

**Comment by mbajur** [comment]
Would be great, thank you! CSS part should be enough as inner_performance does not and probably will not use any bootstrap JS anytime soon or maybe even never :)
